//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AHCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderId { get; set; }
        public string UserID { get; set; }
        public int ProductID { get; set; }
        public int Amount { get; set; }
        public int Price { get; set; }
        public int Total { get; set; }
        public System.DateTime OrderDate { get; set; }
        public bool isPay { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
